# NeurondB Documentation Configuration
# Advanced AI Database Extension for PostgreSQL
# Copyright (c) 2024-2025, pgElephant, Inc. <admin@pgelephant.com>

site_name: NeurondB Documentation
site_description: Advanced AI Database Extension for PostgreSQL - Vector Search, ML Inference, and Hybrid Search
site_author: pgElephant, Inc.
site_url: https://pgelephant.com/neurondb
copyright: Copyright &copy; 2024-2025 pgElephant, Inc.

# Repository
repo_name: pgElephant/NeurondB
repo_url: https://github.com/pgElephant/NeurondB
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - toc.integrate
  
  icon:
    repo: fontawesome/brands/github
    logo: material/brain
    
  favicon: assets/favicon.ico

# Navigation Structure
nav:
  - Home: index.md
  
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  
  - Features:
    - Vector Types: features/vector-types.md
  
  - Machine Learning:
    - Embedding Generation: ml/embeddings.md

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra Configuration
extra:
  version:
    provider: mike
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pgelephant2025
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pgelephant
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pgelephant
    - icon: fontawesome/solid/envelope
      link: mailto:admin@pgelephant.com
  
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  
  generator: false

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

